bowtie_align:
  - software/bowtie/align/**
  - software/bowtie/index/**
  - tests/software/bowtie/**

bowtie_index:
  - software/bowtie/index/**
  - tests/software/bowtie/**

bwa_index:
  - software/bwa/index/**
  - tests/software/bwa/**

bwa_mem:
  - software/bwa/mem/**
  - tests/software/bwa/**

fastqc:
  - software/fastqc/**
  - tests/software/fastqc/**

gffread:
  - software/gffread/**
  - tests/software/gffread/**

multiqc:
  - software/multiqc/**
  - tests/software/multiqc/**

picard_collectmultiplemetrics:
  - software/picard/collectmultiplemetrics/**
  - tests/software/picard/**

picard_markduplicates:
  - software/picard/markduplicates/**
  - tests/software/picard/**

picard_mergesamfiles:
  - software/picard/mergesamfiles/**
  - tests/software/picard/**

preseq_lcextrap:
  - software/preseq/lcextrap/**
  - tests/software/preseq/**

samtools_flagstat:
  - software/samtools/flagstat/**
  - tests/software/samtools/**

samtools_idxstats:
  - software/samtools/idxstats/**
  - tests/software/samtools/**

samtools_index:
  - software/samtools/index/**
  - tests/software/samtools/**

samtools_sort:
  - software/samtools/sort/**
  - tests/software/samtools/**

samtools_stats:
  - software/samtools/stats/**
  - tests/software/samtools/**

stringtie:
      - software/stringtie/**
      - tests/software/stringtie/**

trimgalore:
  - software/trimgalore/**
  - tests/software/trimgalore/**

ucsc_bedgraphtobigwig:
  - software/ucsc/bedgraphtobigwig/**
  - tests/software/ucsc/**
