name: "vsearch_usearchglobal"
description: Compare target sequences to fasta-formatted query sequences using global pairwise alignment.
keywords:
  - vsearch
  - usearch
  - alignment
  - fasta
tools:
  - "vsearch":
      description: "VSEARCH is a versatile open-source tool for microbiome analysis, including chimera detection, clustering, dereplication and rereplication, extraction, FASTA/FASTQ/SFF file processing, masking, orienting, pair-wise alignment, restriction site cutting, searching, shuffling, sorting, subsampling, and taxonomic classification of amplicon sequences for metagenomics, genomics, and population genetics. (USEARCH alternative)"
      homepage: "https://github.com/torognes/vsearch"
      documentation: "None"
      tool_dev_url: "https://github.com/torognes/vsearch"
      doi: "doi: 10.7717/peerj.2584"
      licence: "['GPL v3-or-later OR BSD-2-clause']"

input:
  - queryfasta:
      type: file
      description: Query sequences in FASTA format
      pattern: "*.{fasta,fa,fna,faa}"
  - db:
      type: file
      description: Reference database file. It may be in FASTA or UDB format.
      pattern: "*"

output:
  - blast6out:
      type: file
      description: Tab delimited results in blast-like format
      pattern: "*.{tsv}" 
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@jtangrot"
