name: bcftoos_
description: foo
keywords:
    - align
    - fasta
    - genome
    - reference
tools:
    - bowtie2:
          description: |
              BCFtools is a set of utilities that manipulate variant calls in the
              Variant Call Format (VCF) and its binary counterpart BCF.
          homepage: http://samtools.github.io/bcftools/bcftools.html
          documentation: http://www.htslib.org/doc/bcftools.html
          doi: 10.1038/nmeth.1923
params:
    - outdir:
          type: string
          description: |
              The pipeline's output directory. By default, the module will
              output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
          type: string
          description: |
              Value for the Nextflow `publishDir` mode parameter.
              Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
          type: boolean
          description: |
              Run the module with Conda using the software specified
              via the `conda` directive
    - singularity_pull_docker_container:
          type: boolean
          description: |
              Instead of directly downloading Singularity images for use with Singularity,
              force the workflow to pull and convert Docker containers instead.
    - save_unaligned:
          type: boolean
          description: Save unaligned reads
input:
    - meta:
          type: map
          description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
    - reads:
          type: file
          description: |
              List of input FastQ files of size 1 and 2 for single-end and paired-end data,
              respectively.
    - index:
          type: file
          description: Bowtie2 genome index files
          pattern: "*.ebwt"
output:
    - bam:
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
    - version:
          type: file
          description: File containing software version
          pattern: "*.{version.txt}"
    - fastq:
          type: file
          description: Unaligned FastQ files
          pattern: "*.fastq.gz"
    - log:
        type: file
        description: Aligment log
        pattern: "*.log"
authors:
    - "@kevinmenden"
    - "@joseespinosa"
    - "@drpatelh"
