name: bwa-mem2 index
description: create indexes for BWA from a fasta file
keywords:
    - index
tools:
    - bwa:
        description: |
            Bwa-mem2 is the next version of the bwa-mem algorithm in bwa.
            It produces alignment identical to bwa and is ~1.3-3.1x faster depending on the use-case, dataset and the running machine.
        homepage: https://github.com/bwa-mem2/bwa-mem2
        documentation: https://github.com/bwa-mem2/bwa-mem2
        arxiv: arXiv:1303.3997
input:
    -
        - input:
            type: file
            description: Input fasta file
            pattern: "*.{fasta,fa}"
output:
    -
        - index:
            type: file
            description: bwa indexes file
            pattern: "*.{fasta,fa}.{amb,ann,bwt,pac,sa}"
authors:
    - @maxulysse
