name: FastQ Screen
description: Run FastQ Screen on sequenced reads
keywords:
    - Quality Control
    - Species Screen
    - Contamination
tools:
    - fastqc:
        description: |
            FastQC gives general quality metrics about your reads.
            It provides information about the quality score distribution
            across your reads, the per base sequence content (%A/C/G/T).
            You get information about adapter contamination and other
            overrepresented sequences.
        homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/
        documentation: https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/_build/html/index.html
input:
    -
        - sample_id:
            type: string
            description: Sample identifier
        - reads:
            type: file
            description: Input FastQ file
output:
    -
        - report:
            type: file
            description: FastQC report
            pattern: *_fastqc.{zip,html}
authors:
    - @felix
