name: fastqc
description: Run FastQC on sequenced reads
keywords:
  - Quality Control
  - QC
  - Adapters
tools:
  - fastqc:
      description: |
        FastQC gives general quality metrics about your reads.
        It provides information about the quality score distribution
        across your reads, the per base sequence content (%A/C/G/T).
        You get information about adapter contamination and other
        overrepresented sequences.
      homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
      documentation: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
output:
  - report:
      type: file
      description: FastQC report
      pattern: "*_fastqc.{zip,html}"
authors:
  - "@drpatelh"
  - "@grst"
  - "@ewels"
  - "@FelixKrueger"
