name: antismash_antismashlite
description: antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters.
keywords:
  - secondary metabolites
  - BGC
  - biosynthetic gene cluster
  - genome mining
  - NRPS
  - RiPP
  - antibiotics
  - prokaryotes
  - bacteria
  - eukaryotes
  - fungi
  - antismash

tools:
  - antismashlite:
      description: "antiSMASH - the antibiotics and Secondary Metabolite Analysis SHell"
      homepage: "https://docs.antismash.secondarymetabolites.org"
      documentation: "https://docs.antismash.secondarymetabolites.org"
      tool_dev_url: "https://github.com/antismash/antismash"
      doi: "10.1093/nar/gkab335"
      licence: "['AGPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - sequence_input:
      type: file
      description: nucleotide sequence file (annotated)
      pattern: "*.{gbk, gb, gbff, genbank, embl}"
  - databases:
      type: directory
      description: downloaded antismash databases e.g. data/databases
      pattern: "*"
  - antismash_dir:
      type: directory
      description: |
        antismash installation folder which is being modified during the antiSMASH database downloading step. The modified files are normally downloaded by download-antismash-databases itself, and must be retrieved by the user by manually running the command within antismash-lite. As this folder cannot be modified within the docker and singularity containers, it needs to be mounted (including all modified files from the downloading step) as a workaround.
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - clusterblast_file:
      type: file
      description: Output of ClusterBlast algorithm
      pattern: "clusterblast/*_c*.txt"
  - css_file:
      type: file
      description: Style sheet containing the formatting of HTML output
      pattern: "css/*.css"
  - image_directory:
      type: directory
      description: image files for web view of antiSMASH results
      pattern: "images"
  - javascript:
      type: file
      description: JavaScript files
      pattern: "js/*.js"
  - knownclusterblast_html:
      type: file
      description: Tables with MIBiG hits in HTML format
      pattern: "knownclusterblast/region*/ctg*.html"
  - knownclusterblast_txt:
      type: file
      description: Tables with MIBiG hits
      pattern: "knownclusterblast/*_c*.txt"
  - svg_files_clusterblast:
      type: file
      description: SVG image showing the % identity of the aligned hits against their queries
      pattern: "svg/clusterblast*.svg"
  - svg_files_knownclusterblast:
      type: file
      description: SVG image showing the % identity of the aligned hits against their queries
      pattern: "svg/knownclusterblast*.svg"
  - gbk_input:
      type: file
      description: Nucleotide sequence + annotations in GenBank format; converted from input file
      pattern: "*.gbk"
  - json_results:
      type: file
      description: Nucleotide sequence + annotations in JSON format; converted from GenBank file (gbk_input)
      pattern: "*.json"
  - log:
      type: file
      description: Contains all the logging output that antiSMASH produced during its run
      pattern: "*.log"
  - zip:
      type: file
      description: Contains a compressed version of the output folder in zip format
      pattern: "*.zip"
  - gbk_results:
      type: file
      description: Nucleotide sequence + annotations in GenBank format; one file per antiSMASH hit
      pattern: "*region*.gbk"
  - clusterblastoutput:
      type: file
      description: Raw BLAST output of known clusters previously predicted by antiSMASH using the built-in ClusterBlast algorithm
      pattern: "clusterblastoutput.txt"
  - html:
      type: file
      description: Graphical web view of results in HTML format
      patterN: "index.html"
  - knownclusterblastoutput:
      type: file
      description: Raw BLAST output of known clusters of the MIBiG database
      pattern: "knownclusterblastoutput.txt"
  - json_sideloading:
      type: file
      description: Sideloaded annotations of protoclusters and/or subregions (see documentation "Annotation sideloading")
      pattern: "regions.js"

authors:
  - "@jasmezz"
