name: bwa mem
description: Performs fastq alignment to a fasta reference using the burrows-wheeler aligner
keywords:
    - mem
    - bwa
    - alignment
tools:
    - bwa:
        description: |
            BWA is a software package for mapping DNA sequences against a large reference genome, such as the human genome.
        homepage: http://bio-bwa.sourceforge.net/
        documentation: http://www.htslib.org/doc/samtools.html
        arxiv: arXiv:1303.3997
input:
    -
        - id:
            type: val
            description: read id for paired-end sequences
        - reads:
            type: file
            description: Input fastq file
            pattern: *.{fastq,fq}
        - genome:
            type: file
            description: Input fasta reference genome
            pattern: *.{fasta,fa}
        - index:
            type: file
            description: bwa indexes file
            pattern: *.{fasta,fa}.{amb,ann,bwt,pac,sa}
output:
    -
        - bam:
            type: file
            description: Output bam file
            pattern: *.bam
        - bamindex:
            type: file
            description: Output bam index file
            pattern: *.bai

authors:
    - @jeremy1805
