name: quast
description: Quality Assessment Tool for Genome Assemblies
keywords:
  - quast
  - assembly
  - quality
tools:
  - star:
      description: |
        QUAST calculate quality metrics for genome assemblies
      homepage: http://bioinf.spbau.ru/quast
      doi:
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - consensus:
      type: map
      description: |
        Groovy Map containing sample information
  - fasta:
      type: file
      description: |
        The genome assembly to be evaluated
  - gff:
      type: file
      description: The genome GFF file

output:
  - report:
      type: file
      description: The lineage report
      pattern: "{prefix}.lineage_report.csv"

  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@drpatelh"
  - "@kevinmenden"
