name: "rtgtools_vcfeval"
description: The VCFeval tool of RTG tools. It is used to evaluate called variants for agreement with a baseline variant set
keywords:
  - benchmarking
  - vcf
  - rtg-tools
tools:
  - "rtgtools":
      description: "RealTimeGenomics Tools -- Utilities for accurate VCF comparison and manipulation"
      homepage: "https://www.realtimegenomics.com/products/rtg-tools"
      documentation: "https://github.com/RealTimeGenomics/rtg-tools"
      tool_dev_url: "https://github.com/RealTimeGenomics/rtg-tools"
      doi: ""
      licence: "['BSD']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - truth_vcf:
      type: file
      description: A standard VCF to compare against
      pattern: "*.{vcf,vcf.gz}"
  - truth_vcf_index:
      type: file
      description: The index of the standard VCF (optional)
      pattern: "*.tbi"
  - query_vcf:
      type: file
      description: A VCF with called variants to benchmark against the standard
      pattern: "*.{vcf,vcf.gz}"
  - query_vcf_index:
      type: file
      description: The index of the called VCF (optional)
      pattern: "*.tbi"
  - truth_regions:
      type: file
      description: A BED file containining the strict regions where VCFeval should only evaluate the fully overlapping variants (optional)
      pattern: "*.bed"
  - evaluation_regions:
      type: file
      description: A BED file containing the regions where VCFeval will evaluate every fully and partially overlapping variant (optional)
      pattern: "*.bed"
  - sdf:
      type: file
      description: The SDF (RTG Sequence Data File) folder of the reference genome
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - logging:
      type: file
      description: Files containing logging from vcfeval
      pattern: "*{done,progress,.log}"
  - true_positives:
      type: file
      description: VCF files containing true positives with their index files
      pattern: "tp.vcf{.gz,.gz.tbi}"
  - true_positives_baseline:
      type: file
      description: VCF files containing baseline true positives with their index files
      pattern: "tp-baseline.vcf{.gz,.gz.tbi}"
  - false_positives:
      type: file
      description: VCF files containing false positives with their index files
      pattern: "fp.vcf{.gz,.gz.tbi}"
  - false_negatives:
      type: file
      description: VCF files containing false negatives with their index files
      pattern: "fn.vcf{.gz,.gz.tbi}"
  - roc:
      type: file
      description: TSV files containing ROC data for the evaluated variants
      pattern: "*.tsv.gz"
  - summary:
      type: file
      description: A TXT file containing the summary of the evaluation
      pattern: "summary.txt"
  - phasing:
      type: file
      description: A TXT file containing the data on the phasing
      pattern: "phasing.txt"

authors:
  - "@nvnieuwk"
