name: "rtgtools_vcfeval"
description: The VCFeval tool of RTG tools. It is used to evaluate called variants for agreement with a baseline variant set
keywords:
  - benchmarking
  - vcf
  - rtg-tools
tools:
  - "rtgtools":
      description: "RealTimeGenomics Tools -- Utilities for accurate VCF comparison and manipulation"
      homepage: "https://www.realtimegenomics.com/products/rtg-tools"
      documentation: "https://github.com/RealTimeGenomics/rtg-tools"
      tool_dev_url: "https://github.com/RealTimeGenomics/rtg-tools"
      doi: ""
      licence: "['BSD']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - truth_vcf:
      type: file
      description: A standard VCF to compare against
      pattern: "*.{vcf,vcf.gz}"
  - truth_vcf_index:
      type: file
      description: The index of the standard VCF (optional)
      pattern: "*.tbi"
  - query_vcf:
      type: file
      description: A VCF with called variants to benchmark against the standard
      pattern: "*.{vcf,vcf.gz}"
  - query_vcf_index:
      type: file
      description: The index of the called VCF (optional)
      pattern: "*.tbi"
  - truth_regions:
      type: file
      description: A BED file containining the strict regions where VCFeval should only evaluate the fully overlapping variants (optional)
      pattern: "*.bed"
  - evaluation_regions:
      type: file
      description: A BED file containing the regions where VCFeval will evaluate every fully and partially overlapping variant (optional)
      pattern: "*.bed"
  - sdf:
      type: file
      description: The SDF (RTG Sequence Data File) folder of the reference genome
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - done:
      type: file
      description: A file containing the message on succesful completion
      pattern: "done"
  - progress:
      type: file
      description: A file containing the simplified logging of the process
      pattern: "progress"
  - vcfeval_log:
      type: file
      description: A file containing the extended logging of the process
      pattern: "*.log"
  - false_negatives_vcf:
      type: file
      description: A VCF file containing the false negative variants
      pattern: "fn.vcf.gz"
  - false_negatives_index:
      type: file
      description: The index file for the false negatives' VCF file
      pattern: "fn.vcf.gz.tbi"
  - false_positive_vcf:
      type: file
      description: A VCF file containing the false positive variants
      pattern: "fp.vcf.gz"
  - false_positives_index:
      type: file
      description: The index file for the false positives' VCF file
      pattern: "fp.vcf.gz.tbi"
  - true_positive_vcf:
      type: file
      description: A VCF file containing the true positive variants
      pattern: "tp.vcf.gz"
  - true_positives_index:
      type: file
      description: The index file for the true positives' VCF file
      pattern: "tp.vcf.gz.tbi"
  - true_positive_baseline_vcf:
      type: file
      description: A VCF file containing the true positive baseline variants
      pattern: "tp-baseline.vcf.gz"
  - true_positives_baseline_index:
      type: file
      description: The index file for the baseline true positives' VCF file
      pattern: "tp-baseline.vcf.gz.tbi"
  - non_snp_roc:
      type: file
      description: A TSV file containing the ROC data for the non-SNP variants
      pattern: "non_snp_roc.tsv.gz"
  - snp_roc:
      type: file
      description: A TSV file containing the ROC data for the SNP variants
      pattern: "snp_roc.tsv.gz"
  - weighted_roc:
      type: file
      description: A TSV file containing the weighted ROC data
      pattern: "weighted_roc.tsv.gz"
  - summary:
      type: file
      description: A TXT file containing the summary of the evaluation
      pattern: "summary.txt"
  - phasing:
      type: file
      description: A TXT file containing the data on the phasing
      pattern: "phasing.txt"

authors:
  - "@nvnieuwk"
