name: Cutadapt
description: cutadapt removes adapter sequences from high-throughput sequencing reads
keywords:
  - Quality Control
  - QC
  - Adapters
tools:
  - fastqc:
      description: |
        Cutadapt finds and removes adapter sequences, primers, poly-A tails and other types of unwanted sequence
        from your high-throughput sequencing reads.

        Cleaning your data in this way is often required: Reads from small-RNA sequencing contain the 3’
        sequencing adapter because the read is longer than the molecule that is sequenced. Amplicon reads 
        start with a primer sequence. Poly-A tails are useful for pulling out RNA from your sample, but 
        often you don’t want them to be in your reads.
      homepage: https://cutadapt.readthedocs.io/en/stable/
      documentation: https://cutadapt.readthedocs.io/en/stable/
input:
  - - sample_id:
        type: string
        description: Sample identifier
    - input_forward_fq:
        type: file
        description: Input FastQ forward read file of the pair
    - input_reverse_fq:
        type: file
        description: Input FastQ reverse read file of the pair
output:
  - - sample_id:
        type: string
        description: Sample identifier
    - output_forward_fq:
        type: file
        description: Output FastQ forward read file of the pair
    - output_reverse_fq:
        type: file
        description: Output FastQ reverse read file of the pair
authors:
  - @piotr-faba-ardigen
