name: bedtools genomecov
description: Returns feature coverage for a given genome in different formats
keywords:
    - genomecov
tools:
    - bedtools:
        description: |
            Bedtools is a software package that provides with a toolset to perform genome arithmetic operations.
        homepage: https://bedtools.readthedocs.io/en/latest/index.html
        documentation: https://bedtools.readthedocs.io/en/latest/index.html
        doi: 10.093/bioinformatics/btq033
input:
    -
        - input_file:
            type: file
            description: Input genomic coordinates file
            pattern: "*.{bam}"
        - chrom_sizes:
            type: file
            description: Genome chromosome sizes
            pattern: "*.{txt,sizes}"

output:
    -
        - index:
            type: stdout,file
            description:
            pattern: "stdout,*.{bed,bedGraph}"
authors:
    - "@JoseEspinosa"
