name: picard_mergesamfiles
on:
  push:
    paths:
      - software/picard/mergesamfiles/**
      - .github/workflows/software/picard_mergesamfiles.yml
      - tests/software/picard/**
  pull_request:
    paths:
      - software/picard/mergesamfiles/**
      - .github/workflows/software/picard_mergesamfiles.yml
      - tests/software/picard/**

jobs:
  ci_test:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          export NXF_VER="20.07.1"
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pip pytest-workflow

      # Test the module
      - run: pytest --tag picard_mergesamfiles --symlink --wt 2
