name: "elprep_merge"
description: Merge split bam/sam chunks in one file
keywords:
  - bam
  - sam
  - merge
tools:
  - "elprep":
      description: "elPrep is a high-performance tool for preparing .sam/.bam files for variant calling in sequencing pipelines. It can be used as a drop-in replacement for SAMtools/Picard/GATK4."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: "['AGPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: List of BAM/SAM chunks to merge
      pattern: "*.{bam,sam}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam:
      type: file
      description: Merged BAM/SAM file
      pattern: "*.{bam,sam}"

authors:
  - "@matthdsm"
