name: "happy"
description: Hap.py is a tool to compare diploid genotypes at haplotype level. Rather than comparing VCF records row by row, hap.py will generate and match alternate sequences in a superlocus. A superlocus is a small region of the genome (sized between 1 and around 1000 bp) that contains one or more variants.
keywords:
  - happy
  - benchmark
  - haplotype
tools:
  - "happy":
      description: "Haplotype VCF comparison tools"
      homepage: "https://www.illumina.com/products/by-type/informatics-products/basespace-sequence-hub/apps/hap-py-benchmarking.html"
      documentation: "https://github.com/Illumina/hap.py"
      tool_dev_url: "https://github.com/Illumina/hap.py"
      doi: ""
      licence: "['BSD-2-clause']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - truth_vcf:
      type: file
      description: gold standard VCF file
      pattern: "*.{vcf,vcf.gz}"
  - query_vcf:
      type: file
      description: VCF file to query
      pattern: "*.{vcf,vcf.gz}"
  - bed:
      type: file
      description: BED file
      pattern: "*.bed"
  - fasta:
      type: file
      description: FASTA file of the reference genome
      pattern: "*.{fa,fasta}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@nvnieuwk"
