name: bwa_mem
on:
  push:
    paths:
      - software/bwa/mem/**
      - .github/workflows/bwa_mem.yml
      - tests/software/bwa/**
  pull_request:
    paths:
      - software/bwa/mem/**
      - .github/workflows/bwa_mem.yml
      - tests/software/bwa/**

jobs:
  ci_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_version: [20.11.0-edge]
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        env:
          NXF_VER: ${{ matrix.nxf_version }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pip pytest-workflow

      # Test the module
      - run: pytest --kwdof --tag bwa_index --symlink --wt 2

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            /tmp/pytest_workflow_*/*/log.out
            /tmp/pytest_workflow_*/*/log.err
