name: cutadapt
on:
  push:
    paths: software/cutadapt/**
  pull_request:
    paths: software/cutadapt/**

jobs:
  run_ci_test:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Test module with paired-end data
        run: |
          cd software/cutadapt/test/
          nextflow run .

      - name: Test module with single-end data
        run: |
          cd software/cutadapt/test/
          nextflow run . --single_end
