on:
  push:
    paths: tools/fastqc/*
  pull_request:
    paths: tools/fastqc/*

jobs:
  run_multiqc:
    runs-on: ubuntu-latest

    steps:

    # Check out the repository
    - uses: actions/checkout@v1

    # Test the module
    - name: FastQC
      run: nextflow run ./tools/fastqc/test/
