name: Pytest-workflow
on: [push, pull_request]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'modules' output variable
      modules: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: '.github/filters.yml'

  test:
    runs-on: ubuntu-latest
    name: CI Test
    needs: changes
    if: needs.changes.outputs.modules != '[]'
    strategy:
      matrix:
        nxf_version: ['20.11.0-edge']
        tags: ['${{ fromJson(needs.changes.outputs.modules) }}']
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: actions/cache@v2
        with:
          path: /usr/local/bin/nextflow
          key: ${{ runner.os }}-nextflow-${{ matrix.nxf_version }}
          restore-keys: |
            ${{ runner.os }}-nextflow-
      - name: Nextflow pytest-workflow
        uses: Emiller88/pytest-workflow-composite-action@master
        with:
          pytest_tags: ${{ matrix.tags }}
          nxf_version: ${{ matrix.nxf_version }}

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            /tmp/pytest_workflow_*/*/.nextflow.log
            /tmp/pytest_workflow_*/*/log.out
            /tmp/pytest_workflow_*/*/log.err
