name: star_genomegenerate
on:
  push:
    paths:
      - software/star/genomegenerate/**
      - .github/workflows/star_genomegenerate.yml
      - tests/software/star/**
  pull_request:
    paths:
      - software/star/index/**
      - .github/workflows/star_genomegenerate.yml
      - tests/software/star/**

jobs:
  ci_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_version: [20.11.0-edge]
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        env:
          NXF_VER: ${{ matrix.nxf_version }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pip pytest-workflow

      # Test the module
      - run: pytest --tag star_genomegenerate --symlink --wt 2
