name: Trim Galore!
on:
  push: {}
  pull_request:
    paths: tools/trim_galore/*

jobs:
  run_ci_test:
    runs-on: ubuntu-latest

    steps:

    # Check out the repository
    - uses: actions/checkout@v1

    - name: Install Nextflow
      run: |
        wget -qO- get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/

    # Test the module
    - run: nextflow run ./tools/trim_galore/test/ -ansi-log false
