name: hmtnote
description: Human mitochondrial variants annotation using HmtVar.
keywords:
  - hmtnote mitochondria annotation
tools:
  - hmtnote:
      description: Human mitochondrial variants annotation using HmtVar.
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ["MIT"]

input:
  - vcf:
      type: file
      description: vcf file
      pattern: "*.{vcf}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf:
      type: file
      description: annotated vcf
      pattern: "*_annotated.vcf"

authors:
  - "@sysbiocoder"
